# Autogenerated file

from token import Token

class Expr:
    class Binary(Expr):
        left : Expr
        operator : Token
        right : Expr

        def __init__(self, left : Expr, operator : Token, right : Expr):
            self.left = left
            self.operator = operator
            self.right = right


    class Grouping(Expr):
        expression : Expr

        def __init__(self, expression : Expr):
            self.expression = expression


    class Literal(Expr):
        value : Object

        def __init__(self, value : Object):
            self.value = value


    class Unary(Expr):
        operator : Token
        right : Expr

        def __init__(self, operator : Token, right : Expr):
            self.operator = operator
            self.right = right


